# region MongoDB Config

MONGO_DB_HOST = "localhost"
MONGO_DB_PORT = 27017
SPLITWISE_DB_NAME = "Splitwise"
USERS_COLLECTIONS_NAME = "Users"
DEBTS_COLLECTIONS_NAME = "Debts"
GROUPS_COLLECTIONS_NAME = "Groups"
ACTIVITIES_COLLECTIONS_NAME = "Activities"

# endregion